# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=264)),
                ('plant_breed', models.CharField(max_length=264)),
                ('time_created', models.DateTimeField()),
                ('location', models.CharField(max_length=264)),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
