# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-16 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Plants',
        ),
    ]
