# Generated by Django 2.1.1 on 2018-09-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='time_created',
        ),
    ]
