# Generated by Django 2.1.1 on 2018-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0002_remove_plant_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
