# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0004_auto_20180916_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
